### ISSUE TITLE
Support specifying hidden image by UUID

### ISSUE THREAD

**Issue by domcleal** [mitchellh/vagrant-rackspace#132]
For older, unsupported operating systems, the images aren't listed in the Rackspace images API and have to be specified in the API by UUID.  More info at http://www.rackspace.com/knowledge_center/article/hidden-base-images

It would be useful if the image could attempt to launch the server if a UUID string was supplied.  Currently it appears to still search the images list by name and ID, but then raises Errors::NoMatchingImage if it cannot be found.

Example configuration: `p.image = '8500226f-b193-4471-9eff-9cba8440bfc8'` (Fedora 19)

**Comment by maxlinc** [comment]
I tried to reproduce this but the hidden image worked for me (using the IAD region). It should be working ever since #101, which was released in v0.1.8. Relevant code is [here](https://github.com/mitchellh/vagrant-rackspace/blob/master/lib/vagrant-rackspace/action/create_server.rb#L189-L192).

Can you check you vagrant-rackspace version, and if you're using a version 0.1.8 provide some additional details that may help reproduce the issue?

**Comment by domcleal** [comment]
So it does, apologies for the noise!  I'd tried it, but had forgotten the Vagrantfile I used wraps the image name in a Regexp, so failed the check in the linked code.  Thanks for the reply.
